/*
 * Source: ProcedureResult.java - Generated by OBCOM SQL Wizard 1.150
 * Author: Alan Ociel Rodriguez Marianjel (ClÃ­nica Alemana de Santiago)
 *
 * Copyright (c) CLÃ�NICA ALEMANA DE SANTIAGO. All rights reserved.
 * 
 * All  rights  to this product are owned by CLÃ�NICA ALEMANA DE SANTIAGO and may
 * only be used under the terms of its associated license document. You may  NOT
 * copy,  modify,  sublicense,  or distribute this source file or portions of it
 * unless previously authorized in writing by CLÃ�NICA ALEMANA  DE  SANTIAGO.  In
 * any  event,  this notice and above copyright must always be included verbatim
 * with this file.
 */

package cl.alemana.cajas;

import java.io.Serializable;

/**
 * Methods common to all procedure results.
 *
 * @author Alan Ociel Rodriguez Marianjel (ClÃ­nica Alemana de Santiago)
 */
public abstract class ProcedureResult implements Serializable
{
    private static final long serialVersionUID = 1L;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code ProcedureResult} instance.
     */
    public ProcedureResult()
    {
    }
}
