/*
 * Source: RegistraEventoResult.java - Generated by OBCOM SQL Wizard 1.150
 * Author: Alan Ociel Rodriguez Marianjel (ClÃ­nica Alemana de Santiago)
 *
 * Copyright (c) CLÃ�NICA ALEMANA DE SANTIAGO. All rights reserved.
 * 
 * All  rights  to this product are owned by CLÃ�NICA ALEMANA DE SANTIAGO and may
 * only be used under the terms of its associated license document. You may  NOT
 * copy,  modify,  sublicense,  or distribute this source file or portions of it
 * unless previously authorized in writing by CLÃ�NICA ALEMANA  DE  SANTIAGO.  In
 * any  event,  this notice and above copyright must always be included verbatim
 * with this file.
 */

package cl.alemana.cajas;

import java.math.BigDecimal;

/**
 * Results of procedure {@code PKG_EVENTOS_PPW.REGISTRA_EVENTO}.
 *
 * <pre>
 * P_COD_ERROR    NUMBER    Input/Output
 * P_GLOSA_ERROR  VARCHAR2  Input/Output
 * </pre>
 *
 * @author Alan Ociel Rodriguez Marianjel (ClÃ­nica Alemana de Santiago)
 */
public class RegistraEventoResult extends ProcedureResult
{
    private static final long serialVersionUID = 1L;
    private BigDecimal codError;
    private String glosaError;

    //--------------------------------------------------------------------------
    //-- Constructor Methods ---------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Constructs a new {@code RegistraEventoResult} instance.
     */
    public RegistraEventoResult()
    {
    }

	public BigDecimal getCodError() {
		return codError;
	}

	public void setCodError(BigDecimal codError) {
		this.codError = codError;
	}

	public String getGlosaError() {
		return glosaError;
	}

	public void setGlosaError(String glosaError) {
		this.glosaError = glosaError;
	}

    //--------------------------------------------------------------------------
    //-- Property Methods ------------------------------------------------------
    //--------------------------------------------------------------------------

}
